// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FileBrowserRpcServiceClient is the client API for FileBrowserRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileBrowserRpcServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	FileList(ctx context.Context, in *FileListRequest, opts ...grpc.CallOption) (*FileListReply, error)
	UploadFile(ctx context.Context, opts ...grpc.CallOption) (FileBrowserRpcService_UploadFileClient, error)
	DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (FileBrowserRpcService_DownloadFileClient, error)
}

type fileBrowserRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileBrowserRpcServiceClient(cc grpc.ClientConnInterface) FileBrowserRpcServiceClient {
	return &fileBrowserRpcServiceClient{cc}
}

func (c *fileBrowserRpcServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := c.cc.Invoke(ctx, "/FileBrowserRpcService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileBrowserRpcServiceClient) FileList(ctx context.Context, in *FileListRequest, opts ...grpc.CallOption) (*FileListReply, error) {
	out := new(FileListReply)
	err := c.cc.Invoke(ctx, "/FileBrowserRpcService/FileList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileBrowserRpcServiceClient) UploadFile(ctx context.Context, opts ...grpc.CallOption) (FileBrowserRpcService_UploadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileBrowserRpcService_ServiceDesc.Streams[0], "/FileBrowserRpcService/UploadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileBrowserRpcServiceUploadFileClient{stream}
	return x, nil
}

type FileBrowserRpcService_UploadFileClient interface {
	Send(*UploadFileRequest) error
	CloseAndRecv() (*UploadFileReply, error)
	grpc.ClientStream
}

type fileBrowserRpcServiceUploadFileClient struct {
	grpc.ClientStream
}

func (x *fileBrowserRpcServiceUploadFileClient) Send(m *UploadFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileBrowserRpcServiceUploadFileClient) CloseAndRecv() (*UploadFileReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadFileReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileBrowserRpcServiceClient) DownloadFile(ctx context.Context, in *DownloadFileRequest, opts ...grpc.CallOption) (FileBrowserRpcService_DownloadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileBrowserRpcService_ServiceDesc.Streams[1], "/FileBrowserRpcService/DownloadFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileBrowserRpcServiceDownloadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileBrowserRpcService_DownloadFileClient interface {
	Recv() (*DownloadFileReply, error)
	grpc.ClientStream
}

type fileBrowserRpcServiceDownloadFileClient struct {
	grpc.ClientStream
}

func (x *fileBrowserRpcServiceDownloadFileClient) Recv() (*DownloadFileReply, error) {
	m := new(DownloadFileReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileBrowserRpcServiceServer is the server API for FileBrowserRpcService service.
// All implementations must embed UnimplementedFileBrowserRpcServiceServer
// for forward compatibility
type FileBrowserRpcServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	FileList(context.Context, *FileListRequest) (*FileListReply, error)
	UploadFile(FileBrowserRpcService_UploadFileServer) error
	DownloadFile(*DownloadFileRequest, FileBrowserRpcService_DownloadFileServer) error
	mustEmbedUnimplementedFileBrowserRpcServiceServer()
}

// UnimplementedFileBrowserRpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileBrowserRpcServiceServer struct {
}

func (UnimplementedFileBrowserRpcServiceServer) Login(context.Context, *LoginRequest) (*LoginReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedFileBrowserRpcServiceServer) FileList(context.Context, *FileListRequest) (*FileListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileList not implemented")
}
func (UnimplementedFileBrowserRpcServiceServer) UploadFile(FileBrowserRpcService_UploadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedFileBrowserRpcServiceServer) DownloadFile(*DownloadFileRequest, FileBrowserRpcService_DownloadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadFile not implemented")
}
func (UnimplementedFileBrowserRpcServiceServer) mustEmbedUnimplementedFileBrowserRpcServiceServer() {}

// UnsafeFileBrowserRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileBrowserRpcServiceServer will
// result in compilation errors.
type UnsafeFileBrowserRpcServiceServer interface {
	mustEmbedUnimplementedFileBrowserRpcServiceServer()
}

func RegisterFileBrowserRpcServiceServer(s grpc.ServiceRegistrar, srv FileBrowserRpcServiceServer) {
	s.RegisterService(&FileBrowserRpcService_ServiceDesc, srv)
}

func _FileBrowserRpcService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileBrowserRpcServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FileBrowserRpcService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileBrowserRpcServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileBrowserRpcService_FileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileBrowserRpcServiceServer).FileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FileBrowserRpcService/FileList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileBrowserRpcServiceServer).FileList(ctx, req.(*FileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileBrowserRpcService_UploadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileBrowserRpcServiceServer).UploadFile(&fileBrowserRpcServiceUploadFileServer{stream})
}

type FileBrowserRpcService_UploadFileServer interface {
	SendAndClose(*UploadFileReply) error
	Recv() (*UploadFileRequest, error)
	grpc.ServerStream
}

type fileBrowserRpcServiceUploadFileServer struct {
	grpc.ServerStream
}

func (x *fileBrowserRpcServiceUploadFileServer) SendAndClose(m *UploadFileReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileBrowserRpcServiceUploadFileServer) Recv() (*UploadFileRequest, error) {
	m := new(UploadFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FileBrowserRpcService_DownloadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileBrowserRpcServiceServer).DownloadFile(m, &fileBrowserRpcServiceDownloadFileServer{stream})
}

type FileBrowserRpcService_DownloadFileServer interface {
	Send(*DownloadFileReply) error
	grpc.ServerStream
}

type fileBrowserRpcServiceDownloadFileServer struct {
	grpc.ServerStream
}

func (x *fileBrowserRpcServiceDownloadFileServer) Send(m *DownloadFileReply) error {
	return x.ServerStream.SendMsg(m)
}

// FileBrowserRpcService_ServiceDesc is the grpc.ServiceDesc for FileBrowserRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileBrowserRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FileBrowserRpcService",
	HandlerType: (*FileBrowserRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _FileBrowserRpcService_Login_Handler,
		},
		{
			MethodName: "FileList",
			Handler:    _FileBrowserRpcService_FileList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadFile",
			Handler:       _FileBrowserRpcService_UploadFile_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadFile",
			Handler:       _FileBrowserRpcService_DownloadFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "filebrowser.proto",
}
